name: uvexpress_admin_web
description: UVExpress E-Ticket Admin Web Panel

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase dependencies
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_analytics: ^10.10.7
  
  # State management
  provider: ^6.1.1
  
  # UI and Navigation
  go_router: ^12.1.3
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  
  # Data handling and utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  
  # Charts and visualization
  fl_chart: ^0.65.0
  
  # Excel/CSV export
  excel: ^4.0.2
  
  # HTTP requests
  http: ^1.1.2
  
  # QR Code generation
  qr_flutter: ^4.1.0
  
  # PDF generation
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Date/Time utilities
  timeago: ^3.6.0
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/