// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVi4bFIlWzIW2H1Gs_1mxnhjQZ0XPXyFM',
    appId: '1:774845116609:web:97e574378399bfabbc6440',
    messagingSenderId: '774845116609',
    projectId: 'e-ticket-2e8d0',
    authDomain: 'e-ticket-2e8d0.firebaseapp.com',
    databaseURL:
        'https://e-ticket-2e8d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-ticket-2e8d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9L9u7hTM5ivm1mi8YnkQiJzvuquUECs0',
    appId: '1:774845116609:android:1136a5b7b1bcfdf0bc6440',
    messagingSenderId: '774845116609',
    projectId: 'e-ticket-2e8d0',
    authDomain: 'e-ticket-2e8d0.firebaseapp.com',
    databaseURL:
        'https://e-ticket-2e8d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-ticket-2e8d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9L9u7hTM5ivm1mi8YnkQiJzvuquUECs0',
    appId: '1:774845116609:ios:1136a5b7b1bcfdf0bc6440',
    messagingSenderId: '774845116609',
    projectId: 'e-ticket-2e8d0',
    authDomain: 'e-ticket-2e8d0.firebaseapp.com',
    databaseURL:
        'https://e-ticket-2e8d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-ticket-2e8d0.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9L9u7hTM5ivm1mi8YnkQiJzvuquUECs0',
    appId: '1:774845116609:ios:1136a5b7b1bcfdf0bc6440',
    messagingSenderId: '774845116609',
    projectId: 'e-ticket-2e8d0',
    authDomain: 'e-ticket-2e8d0.firebaseapp.com',
    databaseURL:
        'https://e-ticket-2e8d0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-ticket-2e8d0.firebasestorage.app',
  );
}
