// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwQ3zahvsXOhFOsJak1PqH00LGMaXAQFo',
    appId: '1:321196714455:web:bbab24f83a6cd5ccfb4392',
    messagingSenderId: '321196714455',
    projectId: 'e-ticket-ff181',
    authDomain: 'e-ticket-ff181.firebaseapp.com',
    storageBucket: 'e-ticket-ff181.appspot.com',
    measurementId: 'G-20HS136FGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwQ3zahvsXOhFOsJak1PqH00LGMaXAQFo',
    appId: '1:321196714455:android:3ff8051f1ee87965fb4392',
    messagingSenderId: '321196714455',
    projectId: 'e-ticket-ff181',
    authDomain: 'e-ticket-ff181.firebaseapp.com',
    storageBucket: 'e-ticket-ff181.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwQ3zahvsXOhFOsJak1PqH00LGMaXAQFo',
    appId: '1:321196714455:ios:3ff8051f1ee87965fb4392',
    messagingSenderId: '321196714455',
    projectId: 'e-ticket-ff181',
    authDomain: 'e-ticket-ff181.firebaseapp.com',
    storageBucket: 'e-ticket-ff181.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwQ3zahvsXOhFOsJak1PqH00LGMaXAQFo',
    appId: '1:321196714455:ios:3ff8051f1ee87965fb4392',
    messagingSenderId: '321196714455',
    projectId: 'e-ticket-ff181',
    authDomain: 'e-ticket-ff181.firebaseapp.com',
    storageBucket: 'e-ticket-ff181.appspot.com',
  );
}
